### ISSUE TITLE
Fails to build when used in a esp32 project with feature "std"

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [WMT-GmbH/pn532#5]
Cargo project generated using template from https://github.com/esp-rs/esp-idf-template
Added `pn532 = { version = "0.2", features = ["std"] }` to dependencies.
Full error log: https://gist.github.com/JohnTheCoolingFan/ca330da3b7e187e28124d98f0573abba

**Comment by dimpolo** [comment]
Thanks for the report!

The `std` feature pulls in the `serialport` crate, which only compiles for some [targets](https://github.com/serialport/serialport-rs#platform-support).

Currently that is all that the `std` feature does, so there is no reason to enable it for the esp32. 
I'll try and document this better 😃

**Comment by JohnTheCoolingFan** [comment]
Alright, thanks for clarifying

**Comment by dimpolo** [comment]
should be documented now
